sisimai/rb-sisimai

lib/sisimai.rb
lib/sisimai/address.rb
lib/sisimai/data.rb
lib/sisimai/data/json.rb
lib/sisimai/time.rb
sisimai.gemspec

Both Oj and JrJackson are faster than JSON module like the following benchmark:
```json-vs-oj.rb
Rehearsal -----------------------------------------------------
Encode using JSON  46.110000   8.590000  54.700000 ( 54.874808)
Encode using Oj    28.170000   0.760000  28.930000 ( 29.016625)
------------------------------------------- total: 83.630000sec
user     system      total        real
Encode using JSON  50.050000   9.220000  59.270000 ( 60.163250)
Encode using Oj    27.940000   0.400000  28.340000 ( 28.484986)
```
JrJackson is faster than Oj !!!
```json-vs-jrjackson.rb
Rehearsal ----------------------------------------------------------
Encode using JSON       43.000000   0.730000  43.730000 ( 37.583855)
Encode using JrJackson  20.930000   0.290000  21.220000 ( 21.397240) …
```

Using Oj or JrJackson (see issue #42)

---

lib/sisimai/data.rb
lib/sisimai/reason.rb
lib/sisimai/smtp/reply.rb
lib/sisimai/smtp/status.rb
set-of-emails/maildir/bsd/rfc3464-28.eml
spec/sisimai/data_spec.rb
spec/sisimai/mta/private-children_spec.rb
spec/sisimai/mta/private-relative_spec.rb
spec/sisimai/mta/public-relative_spec.rb
spec/sisimai/smtp/reply_spec.rb
spec/sisimai/smtp/status_spec.rb

Imported from https://github.com/sisimai/p5-Sisimai/pull/165

Implement new reason "delivered"

---

lib/sisimai/mail/maildir.rb

Fixed Issue #55 
[summary]
- add instance variable "@count" (initialized as 0)
- add @count to rwaccessor
- fixed bug code
[diff]
- add instance variable @count (initialized as 0)
- add @count to rwaccessor
- Fix code line:43
- return nil unless self.offset < self.size
+ return nil unless self.count  < self.size
- Add code line:75
+ self.count += 1
- Fix code line:76
- seekhandle.close unless self.offset < self.size
+ seekhandle.close unless self.count < self.size

Fixed Issue #55

---

Changes
lib/sisimai/reason/rejected.rb
lib/sisimai/reason/securityerror.rb
lib/sisimai/reason/toomanyconn.rb

Follow https://github.com/sisimai/p5-Sisimai/pull/207

Add some error message patterns from Amazon SES SMTP endpoint

---

Changes
lib/sisimai/message/email.rb
set-of-emails/maildir/bsd/rfc3834-06.eml
spec/sisimai/mail/maildir_spec.rb
spec/sisimai/mta/public-relative_spec.rb

Issue 65 vacation message

---

lib/sisimai/msp/us/office365.rb

Perl last operator to Ruby break statement

Fix break statement

---

sisimai-java.gemspec
sisimai.gemspec

Remove a condition for the dependent JSON modules

---

ChangeLog.md
lib/sisimai/bite.rb
lib/sisimai/bite/email.rb
lib/sisimai/bite/json.rb
lib/sisimai/bite/json/sendgrid.rb
lib/sisimai/version.rb
set-of-emails/jsonobj/json-sendgrid-12.json
set-of-emails/jsonobj/json-sendgrid-13.json
set-of-emails/jsonobj/json-sendgrid-14.json
spec/sisimai/bite/json/code.rb
spec/sisimai/bite/json/public-sendgrid_spec.rb

Import Pull-Request from https://github.com/sisimai/p5-Sisimai/pull/233

Sisimai 4221p1

---

ChangeLog.md
lib/sisimai/reason/blocked.rb
lib/sisimai/reason/mailboxfull.rb
lib/sisimai/reason/mesgtoobig.rb
lib/sisimai/reason/rejected.rb
lib/sisimai/reason/securityerror.rb
lib/sisimai/reason/spamdetected.rb
lib/sisimai/reason/suspend.rb
lib/sisimai/reason/toomanyconn.rb
lib/sisimai/reason/userunknown.rb
lib/sisimai/rhost.rb
lib/sisimai/rhost/franceptt.rb
set-of-emails/maildir/bsd/email-sendmail-45.eml
set-of-emails/maildir/bsd/email-sendmail-46.eml
set-of-emails/maildir/bsd/rfc3464-33.eml
set-of-emails/maildir/bsd/rhost-franceptt-01.eml
set-of-emails/maildir/bsd/rhost-franceptt-02.eml
spec/sisimai/bite/email/private-rfc3464_spec.rb
spec/sisimai/bite/email/public-rfc3464_spec.rb
spec/sisimai/bite/email/public-sendmail_spec.rb
spec/sisimai/mail/maildir_spec.rb
spec/sisimai/rhost/franceptt_spec.rb
spec/sisimai/rhost_spec.rb

- Import from sisimai/p5-Sisimai#244
- Support SMTP error codes of Orange (orange.fr) and La Poste (laposte.net)

Implement Sisimai::Rhost::FrancePTT

---

lib/sisimai/address.rb
lib/sisimai/bite/email/exchange2007.rb
lib/sisimai/bite/email/zoho.rb
lib/sisimai/bite/json/amazonses.rb
lib/sisimai/data.rb
lib/sisimai/string.rb

Use String#strip, String#chomp instead of String.sub

---

lib/sisimai/reason/contenterror.rb
lib/sisimai/reason/exceedlimit.rb
lib/sisimai/reason/expired.rb
lib/sisimai/reason/hasmoved.rb
lib/sisimai/reason/hostunknown.rb
lib/sisimai/reason/mailboxfull.rb
lib/sisimai/reason/mesgtoobig.rb
lib/sisimai/reason/networkerror.rb
lib/sisimai/reason/norelaying.rb
lib/sisimai/reason/notaccept.rb
lib/sisimai/reason/policyviolation.rb
lib/sisimai/reason/rejected.rb
lib/sisimai/reason/suspend.rb
lib/sisimai/reason/systemerror.rb
lib/sisimai/reason/systemfull.rb
lib/sisimai/reason/toomanyconn.rb
lib/sisimai/reason/vacation.rb
lib/sisimai/reason/virusdetected.rb

All the regular expressions have been converted to fixed strings, import pull-request sisimai/p5-Sisimai#268

Less regular expression in Sisimai::Reason

---

lib/sisimai/bite/email/ezweb.rb
lib/sisimai/bite/email/kddi.rb

sisimai/p5-Sisimai#232
http://news.kddi.com/kddi/corporate/newsrelease/2017/08/22/2637.html

Pre-Updates for new domain of EZweb

---

lib/sisimai/bite/email/amazonses.rb
lib/sisimai/bite/email/aol.rb
lib/sisimai/bite/email/biglobe.rb
lib/sisimai/bite/email/courier.rb
lib/sisimai/bite/email/domino.rb
lib/sisimai/bite/email/einsundeins.rb
lib/sisimai/bite/email/exim.rb
lib/sisimai/bite/email/gmx.rb
lib/sisimai/bite/email/google.rb
lib/sisimai/bite/email/gsuite.rb
lib/sisimai/bite/email/kddi.rb
lib/sisimai/bite/email/mailru.rb
lib/sisimai/bite/email/messagingserver.rb
lib/sisimai/bite/email/mxlogic.rb
lib/sisimai/bite/email/notes.rb
lib/sisimai/bite/email/opensmtpd.rb
lib/sisimai/bite/email/outlook.rb
lib/sisimai/bite/email/qmail.rb
lib/sisimai/bite/email/receivingses.rb
lib/sisimai/bite/email/verizon.rb
lib/sisimai/bite/email/x4.rb
lib/sisimai/bite/email/zoho.rb
lib/sisimai/mda.rb

import pull request sisimai/p5-Sisimai#278

Less regular expression in Sisimai::Bite::Email

---

lib/sisimai.rb
lib/sisimai/mail.rb
lib/sisimai/mail/memory.rb
spec/sisimai/mail/memory_spec.rb
spec/sisimai_spec.rb

Import Pull-Request sisimai/p5-Sisimai#286

Sisimai::Mail::Memory

---

lib/sisimai/bite/email/amazonses.rb
lib/sisimai/bite/email/amazonworkmail.rb
lib/sisimai/bite/email/aol.rb
lib/sisimai/bite/email/bigfoot.rb
lib/sisimai/bite/email/courier.rb
lib/sisimai/bite/email/exim.rb
lib/sisimai/bite/email/facebook.rb
lib/sisimai/bite/email/gsuite.rb
lib/sisimai/bite/email/messagelabs.rb
lib/sisimai/bite/email/outlook.rb
lib/sisimai/bite/email/postfix.rb
lib/sisimai/bite/email/receivingses.rb
lib/sisimai/bite/email/sendgrid.rb
lib/sisimai/bite/email/sendmail.rb
lib/sisimai/bite/email/x5.rb
lib/sisimai/bite/email/yandex.rb
lib/sisimai/data.rb
lib/sisimai/rfc1894.rb
spec/sisimai/bite/email/code.rb
spec/sisimai/rfc1894_spec.rb

Import https://github.com/sisimai/p5-Sisimai/pull/299

Sisimai::RFC1894

---

lib/sisimai/rhost.rb
lib/sisimai/rhost/iua.rb
set-of-emails/maildir/bsd/rhost-iua-01.eml
spec/sisimai/mail/maildir_spec.rb
spec/sisimai/rhost/iua_spec.rb
spec/sisimai/rhost_spec.rb

- Import https://github.com/sisimai/p5-Sisimai/pull/340

Sisimai::Rhost::IUA

---

.travis.yml
lib/sisimai/lhost/einsundeins.rb
lib/sisimai/lhost/postfix.rb
lib/sisimai/rhost/franceptt.rb
set-of-emails/maildir/bsd/email-einsundeins-03.eml
set-of-emails/maildir/bsd/rhost-franceptt-04.eml
set-of-emails/maildir/bsd/rhost-franceptt-05.eml
set-of-emails/maildir/bsd/rhost-franceptt-06.eml
sisimai.gemspec
spec/sisimai/lhost/private-einsundeins_spec.rb
spec/sisimai/lhost/public-einsundeins_spec.rb
spec/sisimai/mail/maildir_spec.rb
spec/sisimai/rhost/franceptt_spec.rb

- Import Pull-Request sisimai/p5-Sisimai#347 created by @aderumier
- Case insensitive error code at `Sisimai::Rhost::FrancePTT`
- Import Pull-Request sisimai/p5-Sisimai#348
- Follow sisimai/p5-Sisimai#347
- `set-of-emails/maildir/bsd/rhost-franceptt-04.eml`
- `set-of-emails/maildir/bsd/email-einsundeins-03.eml`
- Code improvement for Sisimai::Lhost::EinsUndEins to set a remote host name: `smtp-in.orange.fr` into `rhost`
- Import Pull-Request sisimai/p5-Sisimai#349 created by @aderumier
- Add 2 error codes at `Sisimai::Rhost::FrancePTT`
- 102: blocked
- 426: suspend
- Import Pull-Request sisimai/p5-Sisimai#350
- Code improvement at `Sisimai::Lhost::Postfix`

Import Pull-Request sisimai/p5-Sisimai#347-350

---

lib/sisimai/lhost/postfix.rb
set-of-emails/maildir/bsd/email-postfix-64.eml
spec/sisimai/lhost/public-postfix_spec.rb
spec/sisimai/mail/maildir_spec.rb

- Import Pull-Request https://github.com/sisimai/p5-Sisimai/pull/351

Enable to make sisimai parse issue-15.eml

---

lib/sisimai/rfc3834.rb
set-of-emails/maildir/bsd/rfc3834-03.eml
spec/sisimai/lhost/public-rfc3834_spec.rb
spec/sisimai/mail/maildir_spec.rb

- Import Pull-Request https://github.com/sisimai/p5-Sisimai/pull/352

Apple iCloud VACATION at RFC3834

---

ChangeLog.md
lib/sisimai/rhost/franceptt.rb
lib/sisimai/version.rb
set-of-emails/maildir/bsd/rhost-franceptt-07.eml
set-of-emails/maildir/bsd/rhost-franceptt-08.eml
spec/sisimai/mail/maildir_spec.rb
spec/sisimai/rhost/franceptt_spec.rb

- Import sisimai/p5-Sisimai#353 and sisimai/p5-Sisimai@a3e73f86 at FrancePTT
- Add 2 error codes from Orange: `505` is `systemerror`, `999` is `blocked`
- Add 2 sample emails: rhost-franceptt-07.eml, 08.eml at set-of-emails/

Import Pull-Request 353 from p5-Sisimai

---

ChangeLog.md
lib/sisimai/rhost/franceptt.rb
set-of-emails/maildir/bsd/rhost-franceptt-10.eml
set-of-emails/maildir/bsd/rhost-franceptt-11.eml
spec/sisimai/mail/maildir_spec.rb
spec/sisimai/rhost/franceptt_spec.rb

- Import sisimai/p5-Sisimai#357 and sisimai/p5-Sisimai#358 at FrancePTT
- Add 2 sample emails: rhost-franceptt-10.eml, 11.eml at set-of-emails/
- Add many error codes and error messages from Orange and La Poste

Import Pull-Request https://github.com/sisimai/p5-Sisimai/pull/357

---

lib/sisimai/message.rb
lib/sisimai/smtp/error.rb

- String[0,1] == 'v'
- String.start_with?('v') is faster than above

Use start with instead of double equals

---

Benchmarks.mk
lib/sisimai/lhost.rb
lib/sisimai/message.rb
lib/sisimai/reason.rb
lib/sisimai/reason/userunknown.rb
spec/sisimai/lhost_spec.rb
spec/sisimai/reason_spec.rb

- Define module path table at `Sisimai::Lhost`, `Sisimai::Reason`, and `Sisimai::Reason::UserUnknown`
- Use the path table above at the dynamic loading (`require`)

Improve require statement

---

lib/sisimai/lhost/amavis.rb
set-of-emails/maildir/bsd/lhost-amavis-03.eml
spec/sisimai/lhost/private-amavis_spec.rb
spec/sisimai/lhost/public-amavis_spec.rb
spec/sisimai/mail/maildir_spec.rb

- Define several error reasons and patterns
- Add `lhost-amavis-03.eml` into sample email directory

Amavis improvement 2020 spring

---

lib/sisimai/arf.rb
set-of-emails/maildir/bsd/arf-24.eml
spec/sisimai/lhost/code.rb
spec/sisimai/lhost/public-arf_spec.rb
spec/sisimai/mail/maildir_spec.rb

- Import Pull-Request from https://github.com/sisimai/p5-Sisimai/pull/386

Multiple lines in "From:" field in the original message part

---

ChangeLog.md
lib/sisimai/data.rb
lib/sisimai/rhost.rb
lib/sisimai/rhost/spectrum.rb
lib/sisimai/version.rb
set-of-emails/maildir/bsd/rhost-spectrum-01.eml
spec/sisimai/mail/maildir_spec.rb
spec/sisimai/rhost/spectrum_spec.rb

- Import Pull-Request from sisimai/p5-sisimai#397
- Reported at sisimai/p5-sisimai#395 from @meir-w
- New MTA module `Sisimai::Rhost::Spectrum` for parsing bounce mails from https://spectrum.com/
- Add `set-of-emails/maildir/bsd/rhost-spectrum-01.eml`

Sisimai::Rhost::Spectrum

---

lib/sisimai/lhost/sendmail.rb
lib/sisimai/reason/notaccept.rb
lib/sisimai/smtp/status.rb
set-of-emails/maildir/bsd/lhost-sendmail-57.eml
spec/sisimai/lhost/private-sendmail_spec.rb
spec/sisimai/lhost/public-sendmail_spec.rb
spec/sisimai/mail/maildir_spec.rb

- sisimai/p5-sisimai#414
- sisimai/set-of-emails#4
- lhost-sendmail-57.eml

Support Null MX: RFC7505 on Sendmail 8.16.1

---

lib/sisimai/lhost/postfix.rb
lib/sisimai/reason/policyviolation.rb
lib/sisimai/rhost/googleapps.rb
set-of-emails/maildir/bsd/lhost-postfix-66.eml
set-of-emails/maildir/bsd/lhost-postfix-67.eml
set-of-emails/maildir/bsd/lhost-postfix-68.eml
set-of-emails/maildir/bsd/lhost-postfix-69.eml
set-of-emails/maildir/bsd/lhost-postfix-70.eml
set-of-emails/maildir/bsd/lhost-postfix-71.eml
set-of-emails/maildir/bsd/lhost-postfix-72.eml
set-of-emails/maildir/bsd/lhost-postfix-73.eml
set-of-emails/maildir/bsd/lhost-sendmail-58.eml
set-of-emails/maildir/bsd/lhost-sendmail-59.eml
spec/sisimai/lhost/private-postfix_spec.rb
spec/sisimai/lhost/private-sendmail_spec.rb
spec/sisimai/lhost/public-postfix_spec.rb
spec/sisimai/lhost/public-sendmail_spec.rb
spec/sisimai/mail/maildir_spec.rb

- Import Pull-Request sisimai/p5-sisimai#418
- DMARC failure is `policyviolation`
- SPF failure is `blocked`

Updates for DMARC/SPF related errors

---

lib/sisimai/lhost/domino.rb
lib/sisimai/lhost/office365.rb
lib/sisimai/order.rb
lib/sisimai/reason/notaccept.rb
lib/sisimai/reason/suspend.rb
lib/sisimai/reason/systemerror.rb
lib/sisimai/reason/virusdetected.rb
test/private/lhost-amazonses.rb
test/private/lhost-domino.rb
test/private/lhost-exchange2007.rb
test/private/lhost-office365.rb
test/private/lhost-postfix.rb
test/private/lhost-sendmail.rb
test/private/rfc3464.rb

Import Pull-Request sisimai/p5-sisimai#432: Add some European languaguages into Office365, Domino

Add some European languages into Office365, Domino.

---

lib/sisimai/data.rb
set-of-emails/maildir/bsd/rfc3464-41.eml
spec/sisimai/lhost/public-rfc3464_spec.rb
spec/sisimai/mail/maildir_spec.rb

- Fix #223 reported by @chahn 
- Register `rfc3464-41.eml` as a sample
- Update related test code files in `./spec`

Fix issue 223: incompatible character encodings: ASCII-8BIT and UTF-8

---

lib/sisimai/lhost/postfix.rb
lib/sisimai/reason/systemerror.rb
lib/sisimai/smtp/transcript.rb
set-of-emails/maildir/bsd/lhost-postfix-75.eml
test/public/lhost-postfix.rb
test/public/mail-maildir-test.rb
test/public/smtp-trascript-test.rb

- Import Pull-Request sisimai/p5-sisimai#445 
- `Sisimai::SMTP::Transcript`
- Parse "transcript of session" log generated by Postfix, Sendmail, and so on
- Call from `Sisimai::Lhost::Postfix`
- New sample email: `lhost-postfix-75.eml`
- New test code: `test/public/smtp-transcript-test.rb`

Sisimai::SMTP::Transcript

---

ChangeLog.md
lib/sisimai/reason/contenterror.rb
lib/sisimai/reason/norelaying.rb
lib/sisimai/reason/systemerror.rb
set-of-emails/maildir/bsd/lhost-postfix-77.eml
set-of-emails/maildir/bsd/lhost-postfix-78.eml
test/private/lhost-postfix.rb
test/public/lhost-postfix.rb
test/public/mail-maildir-test.rb

- Add sample emails bounced from Amazon SES
- `lhost-postfix-77.eml` (norelaying)
- `lhost-postfix-78.eml` (contenterror)

Amazon SES / 2022 Aug.

---

lib/sisimai/lhost/sendgrid.rb
lib/sisimai/rfc1894.rb
lib/sisimai/rfc3464.rb
test/public/rfc1894-test.rb

- Reduce regular expressions
- Import Pull-Request sisimai/p5-sisimai#486

Sisimai::RFC3464 Calls Sisimai::RFC1894

---

ChangeLog.md
lib/sisimai/mime.rb
lib/sisimai/version.rb

- Fix code when an encoding name is "b" (lower case)
- #251

Fix Sisimai::MIME.mimedecoding

---

lib/sisimai/datetime.rb
lib/sisimai/lhost/amazonses.rb
lib/sisimai/lhost/aol.rb
lib/sisimai/lhost/biglobe.rb
lib/sisimai/lhost/courier.rb
lib/sisimai/lhost/einsundeins.rb
lib/sisimai/lhost/exchange2003.rb
lib/sisimai/lhost/exchange2007.rb
lib/sisimai/lhost/exim.rb
lib/sisimai/lhost/ezweb.rb
lib/sisimai/lhost/facebook.rb
lib/sisimai/lhost/gmail.rb
lib/sisimai/lhost/gmx.rb
lib/sisimai/lhost/imailserver.rb
lib/sisimai/lhost/mailru.rb
lib/sisimai/lhost/receivingses.rb
lib/sisimai/message.rb
lib/sisimai/rfc2045.rb
lib/sisimai/rfc5322.rb
test/private/lhost-exchange2007.rb
test/private/lhost-exim.rb
test/public/datetime-test.rb
test/public/lhost-exchange2007.rb
test/public/rfc5322-test.rb

- Reduce Regular Expressions in some files
- Remove the following methods from `Sisimai::DateTime`
- `to_second`
- `dayofweek`
- Remove a private sample for Exim(1102)

Reduce Regular Expressions 7e75
